# Generated by Django 4.2.6 on 2023-10-30 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0003_projectgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectgroup',
            name='assistants',
            field=models.ManyToManyField(related_name='assistant', to=settings.AUTH_USER_MODEL, verbose_name='Ассистенты'),
        ),
        migrations.AlterField(
            model_name='projectgroup',
            name='group_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор группы'),
        ),
        migrations.AlterField(
            model_name='projectgroup',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.project', verbose_name='Проект'),
        ),
    ]
